### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by BomScoob12** [BomScoob12/WebProjectIT01#1]
# Web todo lists
### Deadline 27 November 2022
- [ ] Design web
- [ ] Index First paragraph [Edit]
- [ ] Index (menu, link, content, picture, etc)
- [ ] content and pictures Activity
- [ ] content and picture Travels
- [ ] content Aboutme link
- [ ] footer
- [ ] theme and text font *important*
- [ ] Diary pages 5-10
- [ ]  Effect hover or animations

**Comment by BomScoob12** [comment]
I have to finish in 18/11/2022
- theme and font
- content Diary (Design)
- footer

**Comment by Ronnixson** [comment]
Ohhhk today it's 7th
